### ISSUE TITLE
Language accent marks are causing UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte

### ISSUE THREAD

**Issue by vegax87** [Omyyyy/pycom#17]
Everytime I try to compile any python file with pycom, it gives me this error, I think it's related to language accent marks in the system language because I haven't used any of these in my python file and I've also checked that I was using UTF-8 in Notepad++
```

PS F:\pycom> pycom .\fibonacci.py
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\Scripts\pycom-script.py", line 33, in <module>
    sys.exit(load_entry_point('pycom', 'console_scripts', 'pycom')())
  File "F:\pycom\src\pycom\main.py", line 199, in main
    run_compile(flags=parsed_args)
  File "F:\pycom\src\pycom\main.py", line 97, in run_compile
    errorstr = errors.cpperrortopycomerror(error.decode(
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
```

**Comment by AnonymouX47** [comment]
It's an issue with the platform you're on (win32)... the character set might be incomplete.
Try using MinGW or MSys2.

> I haven't used any of these in my python file
It's due to characters in a C++ compiler error message (take note of the `cpperrortopycomerror()`), not from your script.

**Comment by 0dminnimda** [comment]
The platform should not be an issue. It'll likely that some file is saved with other encoding but code is assumes it's utf-8

**Comment by 0dminnimda** [comment]
Oh yeah, it's not about files at all, the problem is in the `error.decode('utf-8')`

On the [line 97](https://github.com/Omyyyy/pycom/blob/6242343e1afb1259ec7f81def7abace1eb7f55c2/src/pycom/main.py#L97) the code is trying to decode a bytes from stderr and it can't decode those as utf-8, not surprisingly
