### ISSUE TITLE
tab parser AttributeError

### ISSUE THREAD

**Issue by aaronsdevera** [Omyyyy/pycom#6]
See traceback error, appears to occur when the `parsetabamount` function tries to parse out tabs in the python script.
```
> pycom -c script.py
Traceback (most recent call last):
  File "/my/path/Library/Python/3.8/bin/pycom", line 33, in <module>
    sys.exit(load_entry_point('pycom.py', 'console_scripts', 'pycom')())
  File "/my/path/to/pycom/pycom.py", line 199, in main
    run_compile(flags=parsed_args)
  File "/my/path/to/pycom/pycom.py", line 53, in run_compile
    compiledcode, tokens = compiler.Compile(
  File "/my/path/to/pycom/compiler.py", line 260, in iteratetokens
    code += "    " * parsetabamount(self.oktokens[i])
  File "/my/path/to/pycom/compiler.py", line 135, in parsetabamount
    return int(str(tabtok[1]).removesuffix(" TAB"))
AttributeError: 'str' object has no attribute 'removesuffix'
```

**Comment by riebecj** [comment]
Could you upload your `script.py`?

**Comment by Omyyyy** [comment]
`AttributeError: 'str' object has no attribute 'removesuffix'`

How exactly? Isn't .removesuffix() an inbuilt string method?

**Comment by Omyyyy** [comment]
Ah, I've figured it out. `.removesuffix()` is a 3.9+ method. The README states that Python 3.10+ is required. Sorry.

**Comment by aaronsdevera** [comment]
thank you forl ooking!
